Update model.functions.R
adding beta.binomial to modelSelection doesn't seem to produce intended effect of including option in selectable list:
Error: Argument 'modelSelection' must be one of 'poisson', 'logistic', 'probit', 'nb', 'custom'

went with 'custom' and edited constants.R to include beta.binomial - may need to change name to GLMMadaptive::beta.binomial due to "do.call(.)" implementation of 'custom' here
also added .setModelCall.betabinomMod<-function(model,info) for shiggles, may be useful later?